# Generated by Django 3.0.4 on 2020-07-17 22:02

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 22, 2, 50, 579667, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
