# Generated by Django 3.0.4 on 2020-03-27 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.DateTimeField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='categories',
            name='date_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='label',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='categories',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='categories',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
