# Generated by Django 3.0.4 on 2020-03-30 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_auto_20200328_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='produto.Categories'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categories',
            name='label',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
