# Generated by Django 3.0.4 on 2020-04-07 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_auto_20200402_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ('rank',)},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('timestamp',)},
        ),
        migrations.AlterField(
            model_name='categories',
            name='label',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='produto.Categories'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
