# Generated by Django 3.0.4 on 2020-04-07 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_auto_20200407_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ('label',)},
        ),
    ]
