# Generated by Django 3.0.4 on 2020-05-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_auto_20200407_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('timestamp', 'name')},
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='label',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
