# Generated by Django 3.0.4 on 2020-07-17 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200717_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='likes',
            new_name='related',
        ),
    ]
